### ISSUE TITLE
Change theme to University of Auckland

### ISSUE THREAD

**Issue by Ryuna001** [UoaWDCC/VPS#50]
- Remove Faculty of Medical Sciences Logo and theme
- Add University of Auckland logo and theme (Blue)

**Comment by arnard76** [comment]
I'm not sure if it is only on my device but I'm seeing the old (Faculty of Medical Sciences) logo as the favicon instead of the UoA logo. When running locally, the favicon is the new one though 🥲.

![image](https://github.com/UoaWDCC/VPS/assets/78939786/fa50314e-fe93-4f03-97be-97302b6ebd5c)


When running locally, the favicon is the new one though 🥲.

![image](https://github.com/UoaWDCC/VPS/assets/78939786/793a788d-b8fc-44c5-965a-6f1e837c663a)

**Comment by arnard76** [comment]
Never mind (ignore ☝️), can't reproduce anymore. Using new logo on deployed site too 😀
