### ISSUE TITLE
Failing Prettier, ESLint and Frontend in github

### ISSUE THREAD

**Issue by djos192** [UoaWDCC/VPS#81]

**Comment by quirked-up** [comment]
The frontend tests display themselves as working but give numerous warnings about lack of act(...). I believe this is coming from some side effects in the ContextProviders not being explicitly mentioned in the tests, which could theoretically behave badly without being caught by the tests. I'm not knowledgeable enough to fix this right now though.

**Comment by quirked-up** [comment]
The main thing causing all the tests to fail was that they were set to use node version 12, but the project uses node v14. I updated this and it fixed all the issues on the branch. I PR'd this #95

**Comment by quirked-up** [comment]
A few tests failed again after pulling, these were caused by some commits that had been made after my initial branch. 
More specifically, its from PRs #76 and #79, both of which changed some parts of the UI, and as such the snapshots used in testing needed to be updated to reflect this. The latter PR also had two stray spaces which caused the prettier to fail.
I made PR #81 to finally fully fix the checks.
